:let mapleader = ","
map <leader>l :set list!

autocmd BufWritePre * %s/\s\+$//e

autocmd BufNewFile,BufReadPost *.md set filetype=markdown
let g:markdown_fenced_languages = ['python']

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
